# Generated by tools/build_hardening_schemas.py. Do not edit independently.
from dataclasses import dataclass
from typing import Literal
from ssr.application import CommandContext, SSRConfig, SchedulingAdmissionToken
from ssr.query.context import ProjectQueryContext

@dataclass(frozen=True, slots=True, kw_only=True)
class Subject:
    kind: Literal['symbol', 'file', 'candidate', 'artifact', 'relationship']
    id: str

@dataclass(frozen=True, slots=True, kw_only=True)
class Reference:
    kind: Literal['SOURCE', 'EVIDENCE', 'ARTIFACT', 'RELATIONSHIP']
    id: str

@dataclass(frozen=True, slots=True, kw_only=True)
class Assertion:
    claim: str
    references: tuple[Reference, ...]

@dataclass(frozen=True, slots=True, kw_only=True)
class Facet:
    facet_id: str
    status: Literal['ESTABLISHED', 'CONTRADICTED', 'UNRESOLVED', 'OUT_OF_SCOPE']
    analysis: str
    references: tuple[Reference, ...]

@dataclass(frozen=True, slots=True, kw_only=True)
class IssueDetails:
    expected_type: Literal['STRING', 'INTEGER', 'BOOLEAN', 'ARRAY', 'OBJECT', 'REFERENCE', 'CONTRACT'] | None
    expected_maximum: int | None
    observed_integer: int | None
    expected_contract: str | None
    reference_kind: Literal['SOURCE', 'EVIDENCE', 'ARTIFACT', 'RELATIONSHIP'] | None

@dataclass(frozen=True, slots=True, kw_only=True)
class Issue:
    code: Literal['INVALID_INPUT', 'UNAUTHORIZED', 'STALE_INPUT', 'STALE_ATTEMPT', 'NOT_FOUND', 'NOT_AVAILABLE', 'CONTRACT_MISMATCH', 'INTEGRITY_FAILURE', 'RECEIPT_PENDING', 'SETTLEMENT_BLOCKED', 'CONTEXT_LIMIT', 'TOKEN_ACCOUNTING_UNAVAILABLE', 'LIMIT_REACHED', 'NO_PROGRESS', 'CONFLICT', 'OUTCOME_UNKNOWN', 'INTERNAL_ERROR']
    location: str
    message: str
    retry_kind: Literal['FIX_INPUT', 'MORE_ANALYSIS', 'RETRY_SAME_OPERATION', 'HOST_RECOVERY', 'NONE']
    repair_action: Literal['CORRECT_FIELD', 'READ_REFERENCED_SOURCE', 'REFRESH_INPUT', 'FETCH_EXACT_RESULT', 'CONTINUE_SAME_CURSOR', 'RETRY_SAME_OPERATION', 'REQUEST_HOST_RECOVERY', 'NONE']
    details: IssueDetails

@dataclass(frozen=True, slots=True, kw_only=True)
class Error:
    contract: Literal['collaborative-v1']
    code: Literal['INVALID_INPUT', 'UNAUTHORIZED', 'STALE_INPUT', 'STALE_ATTEMPT', 'NOT_FOUND', 'NOT_AVAILABLE', 'CONTRACT_MISMATCH', 'INTEGRITY_FAILURE', 'RECEIPT_PENDING', 'SETTLEMENT_BLOCKED', 'CONTEXT_LIMIT', 'TOKEN_ACCOUNTING_UNAVAILABLE', 'LIMIT_REACHED', 'NO_PROGRESS', 'CONFLICT', 'OUTCOME_UNKNOWN', 'INTERNAL_ERROR']
    message: str
    correlation_id: str
    issues: tuple[Issue, ...]
    omitted_issue_count: int
    commit_state: Literal['NONE', 'PREPARED', 'COMMITTED', 'UNKNOWN']

@dataclass(frozen=True, slots=True, kw_only=True)
class AttemptIdentity:
    review_run_id: str
    snapshot_id: str
    task_id: str
    agent_run_id: str
    attempt_number: int
    control_generation: int

@dataclass(frozen=True, slots=True, kw_only=True)
class InputRevision:
    contract: Literal['input-v1']
    review_run_id: str
    snapshot_id: str
    task_id: str
    generation: int
    predecessor_digest: str | None
    assignment_digest: str
    policy_digest: str
    material_manifest_hash: str
    request_manifest_hash: str
    checkpoint_id: str | None
    checkpoint_hash: str | None
    required_delta_manifest_hash: str

@dataclass(frozen=True, slots=True, kw_only=True)
class InputTokenPayload:
    contract: Literal['input-token-v1']
    key_id: str
    identity: AttemptIdentity
    revision_id: str
    revision_hash: str
    required_delta_manifest_hash: str

@dataclass(frozen=True, slots=True, kw_only=True)
class OriginCall:
    call_id: str
    call_ordinal: int
    tool_name: str
    arguments_hash: str

@dataclass(frozen=True, slots=True, kw_only=True)
class TranscriptPrefix:
    contract: Literal['transcript-prefix-v1']
    capture_id: str
    capture_identity_hash: str
    execution_contract_hash: str
    identity: AttemptIdentity
    request_id: str
    response_id: str
    end_record_sequence: int
    record_count: int
    total_bytes: int
    head_hash: str
    request_hash: str
    response_hash: str
    parent_prefix_hash: str | None

@dataclass(frozen=True, slots=True, kw_only=True)
class CaptureProof:
    mode: Literal['REQUIRED', 'OPTIONAL', 'OFF']
    disposition: Literal['VERIFIED', 'OPTIONAL_UNAVAILABLE', 'DISABLED']
    prefix_id: str | None
    prefix_hash: str | None

@dataclass(frozen=True, slots=True, kw_only=True)
class RuntimePrefix:
    contract: Literal['runtime-prefix-v1']
    identity: AttemptIdentity
    execution_contract_hash: str
    input_revision_hash: str
    request_id: str
    response_id: str
    request_hash: str
    response_hash: str
    end_event_sequence: int
    event_chain_hash: str
    parent_prefix_hash: str | None
    delivery_manifest_hash: str
    origin_calls: tuple[OriginCall, ...]
    transcript: CaptureProof

@dataclass(frozen=True, slots=True, kw_only=True)
class RequestBinding:
    contract: Literal['request-binding-v1']
    identity: AttemptIdentity
    request_id: str
    request_hash: str
    input_revision_id: str
    input_revision_hash: str
    input_token_hash: str
    delivered_delta_manifest_hash: str
    delivery_manifest_hash: str
    status: Literal['PREPARED', 'OBSERVED']
    response_id: str | None
    response_hash: str | None

@dataclass(frozen=True, slots=True, kw_only=True)
class RequestEvent:
    contract: Literal['runtime-event-v2']
    sequence: int
    kind: Literal['MODEL_REQUEST']
    request_id: str
    request_hash: str
    input_revision_hash: str
    delivery_manifest_hash: str
    input_token_hash: str
    token_count: int
    reserved_output_tokens: int
    counter_digest: str

@dataclass(frozen=True, slots=True, kw_only=True)
class ResponseEvent:
    contract: Literal['runtime-event-v2']
    sequence: int
    kind: Literal['MODEL_RESPONSE']
    request_id: str
    response_id: str
    request_hash: str
    response_hash: str
    complete: bool
    stop_reason: Literal['TOOL_CALLS', 'END_TURN', 'MAX_OUTPUT', 'REFUSAL']
    origin_calls: tuple[OriginCall, ...]
    input_tokens: int | None
    output_tokens: int | None

@dataclass(frozen=True, slots=True, kw_only=True)
class ToolEvent:
    contract: Literal['runtime-event-v2']
    sequence: int
    kind: Literal['TOOL_EFFECT', 'TOOL_RESULT_DELIVERED']
    response_id: str
    call_id: str
    call_ordinal: int
    operation_id: str | None
    arguments_hash: str
    result_hash: str
    committed: bool
    delivery_manifest_hash: str | None

@dataclass(frozen=True, slots=True, kw_only=True)
class TerminalEvent:
    contract: Literal['runtime-event-v2']
    sequence: int
    kind: Literal['AGENT_TERMINAL']
    status: Literal['COMPLETED', 'INVALID_OUTPUT', 'TIMED_OUT', 'REFUSED', 'FAILED', 'CANCELLED']
    termination_reason: Literal['RESULT_ACCEPTED', 'YIELDED', 'INVALID_OUTPUT', 'TIMED_OUT', 'REFUSED', 'FAILED', 'CANCELLED']
    yield_intent_id: str | None
    result_artifact_id: str | None
    final_input_revision_hash: str
    settlement_manifest_hash: str

@dataclass(frozen=True, slots=True, kw_only=True)
class FocusedResult:
    contract: Literal['focused-result-v1']
    input_token: str
    question: str
    checked_subjects: tuple[Subject, ...]
    observations: tuple[Assertion, ...]
    counterevidence: tuple[Assertion, ...]
    assumptions: tuple[str, ...]
    unknowns: tuple[str, ...]
    disposition: Literal['LEADS_RECORDED', 'NO_SUPPORTED_LEAD', 'INCONCLUSIVE']
    registered_lead_ids: tuple[str, ...]
    next_context_request_ids: tuple[str, ...]

@dataclass(frozen=True, slots=True, kw_only=True)
class ContextAnswer:
    contract: Literal['context-answer-v1']
    input_token: str
    request_id: str
    request_revision: int
    scope_checked: tuple[Subject, ...]
    facets: tuple[Facet, ...]
    answer: str
    assumptions: tuple[str, ...]
    counterevidence: tuple[Assertion, ...]
    unknowns: tuple[str, ...]
    outcome: Literal['ANSWERED', 'CONTRADICTED_ASSUMPTION', 'INCONCLUSIVE', 'NEEDS_DIFFERENT_SCOPE']

@dataclass(frozen=True, slots=True, kw_only=True)
class ContextResult:
    contract: Literal['context-result-v1']
    input_token: str
    answer_artifact_id: str
    answer_artifact_hash: str
    request_id: str
    request_revision: int
    disposition: Literal['ANSWERED', 'CONTRADICTED_ASSUMPTION', 'INCONCLUSIVE', 'NEEDS_DIFFERENT_SCOPE']

@dataclass(frozen=True, slots=True, kw_only=True)
class SynthesisManifest:
    contract: Literal['synthesis-manifest-v1']
    task_id: str
    input_revision_hash: str
    snapshot_id: str
    file_id: str
    graph_id: str
    graph_hash: str
    policy_hash: str
    item_count: int
    items_root: str
    required_decision_count: int
    required_decisions_root: str
    evidence_closure_root: str
    origin_manifest_root: str

@dataclass(frozen=True, slots=True, kw_only=True)
class SynthesisManifestItem:
    ordinal: int
    item_key: str
    kind: Literal['CONTRIBUTION', 'RECONCILIATION_OBLIGATION', 'RESIDUAL_FILE_OBLIGATION']
    unit_id: str | None
    unit_input_hash: str | None
    artifact_id: str | None
    artifact_hash: str | None
    adoption_receipt_id: str | None
    subject_set_hash: str
    evidence_closure_hash: str
    dependency_closure_hash: str
    origin_manifest_hash: str
    required_decision_key: str | None

@dataclass(frozen=True, slots=True, kw_only=True)
class SynthesisDecision:
    kind: Literal['DECISION']
    key: str
    action: Literal['RETAIN', 'MERGE', 'REJECT_PROPOSAL', 'UNRESOLVED', 'FILE_ANALYSIS']
    origin_set_key: str | None
    evidence_set_key: str | None
    rationale: str
    supersedes_digest: str | None

@dataclass(frozen=True, slots=True, kw_only=True)
class SynthesisReferences:
    kind: Literal['REFERENCE_SET_PAGE']
    set_key: str
    page_index: int
    references: tuple[Reference, ...]
    final_page: bool

@dataclass(frozen=True, slots=True, kw_only=True)
class SynthesisStage:
    contract: Literal['synthesis-stage-v1']
    input_token: str
    session_id: str
    manifest_hash: str
    expected_revision: int
    entries: tuple[SynthesisDecision | SynthesisReferences, ...]

@dataclass(frozen=True, slots=True, kw_only=True)
class SynthesisSeal:
    contract: Literal['synthesis-seal-v1']
    input_token: str
    session_id: str
    manifest_hash: str
    expected_revision: int
    journal_hash: str

@dataclass(frozen=True, slots=True, kw_only=True)
class SynthesisReceipt:
    session_id: str
    manifest_hash: str
    revision: int
    journal_hash: str
    committed_entry_count: int
    operation_id: str

@dataclass(frozen=True, slots=True, kw_only=True)
class InvestigationProgress:
    contract: Literal['investigation-progress-v1']
    input_token: str
    candidate_revision: int
    outcome: Literal['NEED_CONTEXT']
    checkpoint_id: str
    request_ids: tuple[str, ...]
    missing_facets: tuple[str, ...]

@dataclass(frozen=True, slots=True, kw_only=True)
class CallRange:
    start_byte: int
    end_byte: int

@dataclass(frozen=True, slots=True, kw_only=True)
class ExpressionRef:
    range: CallRange
    kind: Literal['NAME', 'ATTRIBUTE', 'CALL', 'SUBSCRIPT', 'LITERAL', 'OTHER']

@dataclass(frozen=True, slots=True, kw_only=True)
class CallArgument:
    ordinal: int
    kind: Literal['POSITIONAL', 'KEYWORD', 'STAR', 'DOUBLE_STAR']
    keyword: str | None
    expression: ExpressionRef
    constant_bool: bool | None

@dataclass(frozen=True, slots=True, kw_only=True)
class CallBinding:
    state: Literal['EXACT', 'AMBIGUOUS', 'UNRESOLVED', 'NOT_SUPPORTED']
    canonical_api: str | None
    basis: Literal['IMPORT_ALIAS', 'FROM_IMPORT', 'BUILTIN_SCOPE', 'LOCAL_DECLARATION', 'SHADOWED', 'DYNAMIC', 'MISSING']
    candidate_symbol_ids: tuple[str, ...]

@dataclass(frozen=True, slots=True, kw_only=True)
class Callsite:
    callsite_id: str
    containing_symbol_id: str | None
    range: CallRange
    callee: ExpressionRef
    receiver: ExpressionRef | None
    arguments: tuple[CallArgument, ...]
    arguments_complete: bool
    binding: CallBinding
    limitations: tuple[str, ...]

@dataclass(frozen=True, slots=True, kw_only=True)
class AdapterCallBinding:
    state: Literal['EXACT', 'AMBIGUOUS', 'UNRESOLVED', 'NOT_SUPPORTED']
    canonical_api: str | None
    basis: Literal['IMPORT_ALIAS', 'FROM_IMPORT', 'BUILTIN_SCOPE', 'LOCAL_DECLARATION', 'SHADOWED', 'DYNAMIC', 'MISSING']
    candidate_local_ids: tuple[str, ...]

@dataclass(frozen=True, slots=True, kw_only=True)
class AdapterCallsite:
    containing_symbol_local_id: str | None
    range: CallRange
    callee: ExpressionRef
    receiver: ExpressionRef | None
    arguments: tuple[CallArgument, ...]
    arguments_complete: bool
    binding: AdapterCallBinding
    limitations: tuple[str, ...]

@dataclass(frozen=True, slots=True, kw_only=True)
class AdapterCallsiteBatch:
    contract: Literal['callsite-adapter-v1']
    file_hash: str
    adapter_id: str
    adapter_version: str
    status: Literal['COMPLETE', 'PARTIAL', 'UNSUPPORTED', 'ERROR']
    calls: tuple[AdapterCallsite, ...]
    next_start_byte: int | None
    limitations: tuple[str, ...]

@dataclass(frozen=True, slots=True, kw_only=True)
class CallsiteBatch:
    contract: Literal['callsite-ir-v1']
    snapshot_id: str
    file_id: str
    file_hash: str
    adapter_id: str
    adapter_version: str
    status: Literal['COMPLETE', 'PARTIAL', 'UNSUPPORTED', 'ERROR']
    calls: tuple[Callsite, ...]
    next_cursor: str | None
    limitations: tuple[str, ...]

@dataclass(frozen=True, slots=True, kw_only=True)
class PageRequest:
    cursor: str | None
    limit: int

@dataclass(frozen=True, slots=True, kw_only=True)
class WorkFilter:
    task_types: tuple[Literal['SYMBOL_REVIEW', 'FILE_REVIEW', 'LINK_REVIEW', 'FOCUSED_ANALYSIS', 'CONTEXT_REVIEW', 'INVESTIGATION', 'FALSIFICATION'], ...]
    states: tuple[Literal['PENDING', 'LEASED', 'RUNNING', 'WAITING_DEPENDENCY', 'COMPLETED', 'FAILED', 'CANCELLED', 'SUPERSEDED', 'SKIPPED'], ...]
    root_work_id: str | None

@dataclass(frozen=True, slots=True, kw_only=True)
class ArtifactFilter:
    subject: Subject
    kinds: tuple[Literal['SYMBOL_RESULT', 'FILE_SYNTHESIS', 'LINK_RESULT', 'FOCUSED_RESULT', 'CONTEXT_ANSWER', 'CONTEXT_RESULT', 'INVESTIGATION_ARGUMENT', 'INVESTIGATION_DISPOSITION', 'INVESTIGATION_PROGRESS', 'FALSIFICATION_VERDICT', 'LEAD_ORIGIN', 'ANALYSIS_OBSERVATION'], ...]
    include_superseded: bool

@dataclass(frozen=True, slots=True, kw_only=True)
class Capabilities:
    contract: Literal['collaborative-v1']
    schema_bundle_hash: str
    sdk_abi_hash: str
    state_contract_hash: str
    runtime_receipt_contract: Literal['2.0']
    prefix_receipt_contract: Literal['1.0']
    supported_task_types: tuple[Literal['SYMBOL_REVIEW', 'FILE_REVIEW', 'LINK_REVIEW', 'FOCUSED_ANALYSIS', 'CONTEXT_REVIEW', 'INVESTIGATION', 'FALSIFICATION'], ...]
    max_page_items: int

@dataclass(frozen=True, slots=True, kw_only=True)
class ResourceCapacity:
    resource_id: str
    kind: Literal['PROVIDER', 'MATCHER', 'HOST']
    route_ids: tuple[str, ...]
    upper_bound: int

@dataclass(frozen=True, slots=True, kw_only=True)
class SlicePlan:
    plan_id: str
    review_run_id: str
    config_hash: str
    contract_hash: str
    control_generation: int
    requested_capacity: int
    effective_capacity: int
    resources: tuple[ResourceCapacity, ...]
    command_input_token_budget: int
    command_output_token_budget: int
    exact_task_id: str | None
    observed_sequence: int
    expires_at: str
    plan_digest: str

@dataclass(frozen=True, slots=True, kw_only=True)
class DriveResult:
    plan_id: str
    started: int
    completed: int
    failed: int
    settling: int
    waiting: int
    still_running: int
    reason: Literal['SLICE_COMPLETE', 'CAPACITY_FULL', 'NO_ELIGIBLE_WORK', 'BUDGET_EXHAUSTED', 'CANCELLED', 'RECOVERY_REQUIRED']
    completion: Literal['ANALYZING', 'COMPLETE', 'COMPLETE_WITH_LIMITATIONS', 'BLOCKED', 'CANCELLED', 'FAILED']

@dataclass(frozen=True, slots=True, kw_only=True)
class WorkSummary:
    task_id: str
    root_work_id: str
    task_type: Literal['SYMBOL_REVIEW', 'FILE_REVIEW', 'LINK_REVIEW', 'FOCUSED_ANALYSIS', 'CONTEXT_REVIEW', 'INVESTIGATION', 'FALSIFICATION']
    state: Literal['PENDING', 'LEASED', 'RUNNING', 'WAITING_DEPENDENCY', 'COMPLETED', 'FAILED', 'CANCELLED', 'SUPERSEDED', 'SKIPPED']
    attempt_id: str | None
    attempt_number: int | None
    input_revision_hash: str
    wait_generation: int | None
    subject_manifest_ref: str
    result_manifest_ref: str | None
    blocker: Literal['DEPENDENCY', 'SETTLING', 'RECEIPT', 'BUDGET', 'PROVIDER', 'CONTEXT', 'NO_PROGRESS', 'INTEGRITY'] | None

@dataclass(frozen=True, slots=True, kw_only=True)
class RequestSummary:
    request_id: str
    revision: int
    producer_task_id: str | None
    state: Literal['REGISTERED', 'ROUTED', 'ANSWER_AVAILABLE', 'CLOSED', 'CANCELLED']
    consumer_count: int
    answer_artifact_id: str | None
    answer_hash: str | None

@dataclass(frozen=True, slots=True, kw_only=True)
class ArtifactSummary:
    artifact_id: str
    kind: Literal['SYMBOL_RESULT', 'FILE_SYNTHESIS', 'LINK_RESULT', 'FOCUSED_RESULT', 'CONTEXT_ANSWER', 'CONTEXT_RESULT', 'INVESTIGATION_ARGUMENT', 'INVESTIGATION_DISPOSITION', 'INVESTIGATION_PROGRESS', 'FALSIFICATION_VERDICT', 'LEAD_ORIGIN', 'ANALYSIS_OBSERVATION']
    payload_hash: str
    producer_task_id: str
    producer_attempt_id: str
    state: Literal['ACCEPTANCE_PENDING', 'AVAILABLE', 'WITHDRAWN', 'REJECTED']
    availability_sequence: int | None
    availability_generation: int
    subject_manifest_ref: str

@dataclass(frozen=True, slots=True, kw_only=True)
class FindingSummary:
    family_id: str
    candidate_id: str
    revision: int
    argument_hash: str
    validity_generation: int
    verdict_artifact_id: str
    state: Literal['CURRENT']
    review_complete: bool

@dataclass(frozen=True, slots=True, kw_only=True)
class Completion:
    review_run_id: str
    status: Literal['ANALYZING', 'COMPLETE', 'COMPLETE_WITH_LIMITATIONS', 'BLOCKED', 'CANCELLED', 'FAILED']
    canonical_total: int
    canonical_complete: int
    required_open: int
    settling_count: int
    receipt_pending_count: int
    unresolved_limitations: int
    blockers: tuple[Literal['INVALID_INPUT', 'UNAUTHORIZED', 'STALE_INPUT', 'STALE_ATTEMPT', 'NOT_FOUND', 'NOT_AVAILABLE', 'CONTRACT_MISMATCH', 'INTEGRITY_FAILURE', 'RECEIPT_PENDING', 'SETTLEMENT_BLOCKED', 'CONTEXT_LIMIT', 'TOKEN_ACCOUNTING_UNAVAILABLE', 'LIMIT_REACHED', 'NO_PROGRESS', 'CONFLICT', 'OUTCOME_UNKNOWN', 'INTERNAL_ERROR'], ...]
    omitted_blocker_count: int
    as_of_sequence: int

@dataclass(frozen=True, slots=True, kw_only=True)
class WorkPage:
    items: tuple[WorkSummary, ...]
    next_cursor: str | None
    exhausted: bool
    as_of_sequence: int

@dataclass(frozen=True, slots=True, kw_only=True)
class RequestPage:
    items: tuple[RequestSummary, ...]
    next_cursor: str | None
    exhausted: bool
    as_of_sequence: int

@dataclass(frozen=True, slots=True, kw_only=True)
class ArtifactPage:
    items: tuple[ArtifactSummary, ...]
    next_cursor: str | None
    exhausted: bool
    as_of_sequence: int

@dataclass(frozen=True, slots=True, kw_only=True)
class FindingPage:
    items: tuple[FindingSummary, ...]
    next_cursor: str | None
    exhausted: bool
    as_of_sequence: int

class CollaborativeReviewService:
    def __init__(self, config: SSRConfig) -> None: ...
    def capabilities(self, context: CommandContext) -> Capabilities: ...
    def plan_collaborative_slice(self, context: CommandContext, *, review_run_id: str, requested_capacity: int, exact_task_id: str | None = None) -> SlicePlan: ...
    def drive_collaborative_slice(self, context: CommandContext, *, plan: SlicePlan, admission_token: SchedulingAdmissionToken) -> DriveResult: ...

class CollaborativeQueryService:
    def __init__(self) -> None: ...
    def list_work(self, context: ProjectQueryContext, *, review_run_id: str, filters: WorkFilter, page: PageRequest) -> WorkPage: ...
    def list_requests(self, context: ProjectQueryContext, *, review_run_id: str, task_id: str | None, page: PageRequest) -> RequestPage: ...
    def list_artifacts(self, context: ProjectQueryContext, *, review_run_id: str, filters: ArtifactFilter, page: PageRequest) -> ArtifactPage: ...
    def list_current_findings(self, context: ProjectQueryContext, *, review_run_id: str, page: PageRequest) -> FindingPage: ...
    def get_review_completion(self, context: ProjectQueryContext, *, review_run_id: str) -> Completion: ...

class CollaborativeServiceError(RuntimeError):
    error: Error
    def __init__(self, error: Error) -> None: ...
